target("Optional1")
    set_kind("binary")
    add_files("main1.cpp")
target_end()

target("Optional2")
    set_kind("binary")
    add_files("main2.cpp")
target_end()

target("Optional3")
    set_kind("binary")
    add_files("main3.cpp")
target_end()

target("Optional4")
    set_kind("binary")
    add_files("main4.cpp")
target_end()

target("Optional5")
    set_kind("binary")
    add_files("main5.cpp")
target_end()

target("Optional6")
    set_kind("binary")
    add_files("main6.cpp")
target_end()

target("Optional7")
    set_kind("binary")
    add_files("main7.cpp")
target_end()

target("Optional8")
    set_kind("binary")
    add_files("main8.cpp")
    set_languages("cxx23")
target_end()

target("Optional9")
    set_kind("binary")
    add_files("main9.cpp")
    set_languages("cxx23")
target_end()
