target("StringView1")
    set_kind("binary")
    add_files("main1.cpp")
    set_languages("cxx20")
target_end()

target("StringView2")
    set_kind("binary")
    add_files("main2.cpp")
    set_languages("cxx20")
target_end()

target("StringView3")
    set_kind("binary")
    add_files("main3.cpp")
    set_languages("cxx20")
target_end()
